const {gql} = require('apollo-server-express');
const typeDefs = gql`
  # Types 
  scalar FileUpload

  type Message {
    "The ID was generated by NeDB"
    _id: ID!
    name: String!
    date: String!
    message: String!
    file: String
  }
  type File {
    url: String!
  }

  # Queries
  type Query {
      "This will retrieve a list of messages using neDB"
      getAllMessages: [Message]!
  }


  # Mutations 
  type Mutation {
    postMessage(name: String!, message: String!, file: String): Boolean!
    uploadImage(file: FileUpload!): String!
  }

  #Subscription
  type Subscription {
    newMessages: [Message!]
  }
`;

module.exports = {typeDefs}


